Repository aws-controllers-k8s/test-infra, pull requests merged in 2021-05, with the labels that each got.

#22 Add ACK core OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file

#23 Dummy gitignore change
  .gitignore
Labels: approved, lgtm

#24 Revert "Merge pull request #23 from RedbackThomson/dummy-test"
  .gitignore
Labels: approved, lgtm

#26 Documentation for Prow job configuration and processes
  docs/infrastructure.md
  docs/prow-jobs.md
  prow/jobs/images/README.md
Labels: approved, lgtm

#27 Squash all PRs in Prow by default
  prow/config/Chart.yaml
  prow/config/templates/config-ConfigMap.yaml
Labels: approved, lgtm

#28 Fix merge commit body and title positions
  prow/config/templates/config-ConfigMap.yaml
Labels: approved

#29 Add PR number to commit title
  prow/config/Chart.yaml
  prow/config/templates/config-ConfigMap.yaml
Labels: approved

#30 Assume service team test role
  docs/onboarding.md
  infra/lib/iam/test-role.ts
  infra/lib/prow-service-accounts.ts
  infra/lib/test-ci-stack.ts
  prow/jobs/images/Dockerfile.test
  prow/jobs/images/wrapper.sh
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jinja/presubmits/e2e_test.jinja2
  prow/jobs/jobs.yaml
Labels: approved, lgtm

#31 Pass `PYTEST_LOG_LEVEL` through to e2e container
  scripts/build-run-test-dockerfile.sh
  scripts/run-tests.sh
Labels: approved, lgtm

#32 Always run e2e tests
  prow/config/Chart.yaml
  prow/config/templates/plugins-ConfigMap.yaml
  prow/jobs/jinja/presubmits/e2e_test.jinja2
  prow/jobs/jobs.yaml
Labels: approved, lgtm

#34 Remove insecure default test role
  infra/lib/iam/test-role.ts
  infra/lib/test-ci-stack.ts
  prow/jobs/images/wrapper.sh
  prow/jobs/jinja/presubmits/e2e_test.jinja2
  prow/jobs/jobs.yaml
Labels: approved, lgtm

#35 Update cluster size and pytest parallel threads
  infra/lib/ci-cluster.ts
  prow/jobs/jinja/presubmits/e2e_test.jinja2
  prow/jobs/jobs.yaml
  scripts/build-run-test-dockerfile.sh
  scripts/run-tests.sh
Labels: approved

#37 Add support for loading incluster kubeconfig for soak tests.
  src/acktest/k8s/resource.py
Labels: approved, lgtm

#38 Fix the loadInClusterKubeConfig condition.
  src/acktest/k8s/resource.py
Labels: approved, lgtm

#39 Remove `always_run` on presubmit jobs
  prow/jobs/jinja/presubmits/e2e_test.jinja2
  prow/jobs/jobs.yaml
Labels: approved, lgtm
