Repository aws-controllers-k8s/test-infra, pull requests merged in 2023-12, with the labels that each got.

#394 Bump boto3 version to `1.33.12`
  requirements.txt
Labels: approved, lgtm

#391 Force controllers e2e tests to run using go `1.21.5`
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#392 Bump Go compiler used to release controllers binaries to 1.21.5
  prow/jobs/images/Dockerfile.auto-generate-controllers
  prow/jobs/images/Dockerfile.auto-update-controllers
  prow/jobs/images/Dockerfile.deploy
  prow/jobs/images/Dockerfile.olm-bundle-pr
  prow/jobs/images/Dockerfile.olm-test
  prow/jobs/images/Dockerfile.test
  prow/jobs/images/build-images.sh
  prow/jobs/images_config.yaml
  prow/jobs/jinja/periodics/label_sync.jinja2
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#395 Add keyspaces to service lists
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm, needs-ok-to-test

#383 chore: support Multiple architecture
  cd/scripts/release-controller.sh
Labels: approved, lgtm, needs-ok-to-test

#399 Improve `api-2.json` metadata parsers
  prow/jobs/images/build-docs.sh
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  tools/ackdiscover/service.py
Labels: approved

#400 Add a `DEBUG` environment variable for `build-docs.sh` script
  prow/jobs/images/build-docs.sh
Labels: approved

#401 Enhance parsing logic of `api-2.json` model files
  prow/jobs/images/build-docs.sh
  tools/ackdiscover/service.py
  tools/requirements.txt
Labels: approved

#403 Add `yq` binary for OLM images
  prow/jobs/images/Dockerfile.docs
  prow/jobs/images/Dockerfile.olm-bundle-pr
  prow/jobs/images/Dockerfile.olm-test
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved

#405 Bump `acktest` dependencies
  requirements.txt
Labels: approved
