Repository aws-controllers-k8s/test-infra, pull requests merged in 2024-08, with the labels that each got.

#462 Onboard new services to prow test infra
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#463 Onboard SES controller to prow
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#467 Increase security token TTL to 2 hours for docs-release prow job
  tools/ackdiscover/ecrpublic.py
Labels: approved, lgtm

#468 Fix ECR public session token expiration in ack-discover
  tools/ackdiscover/controller.py
  tools/ackdiscover/ecrpublic.py
  tools/cmd/ack-discover
Labels: approved, lgtm

#469 Fix infinite loop in `ecrpublic::DescribeImages` pagination
  tools/ackdiscover/ecrpublic.py
Labels: approved, lgtm

#465 Add upgrade-go-version prow job and patch prow image versions
  build_config.yaml
  prow/jobs/images/Dockerfile.upgrade-go-version
  prow/jobs/images_config.yaml
  prow/jobs/jinja/periodics/upgrade-go-version.jinja2
  prow/jobs/tools/cmd/command/ecrpublic/client.go
  prow/jobs/tools/cmd/command/ecrpublic/client_token.go
  prow/jobs/tools/cmd/command/ecrpublic/client_url.go
  prow/jobs/tools/cmd/command/github.go
  prow/jobs/tools/cmd/command/helpers.go
  prow/jobs/tools/cmd/command/root.go
  prow/jobs/tools/cmd/command/upgrade_go_version.go
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
  prow/jobs/tools/cmd/go.mod
  prow/jobs/tools/cmd/go.sum
  prow/jobs/tools/cmd/main.go
Labels: approved, lgtm

#470 Rewrite generator.py in Golang
  go.mod
  go.sum
  prow/jobs/gen_labels.py
  prow/jobs/generator.go
  prow/jobs/generator.py
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/config/label_sync.tpl
  prow/jobs/templates/periodics/docs_release.tpl
  prow/jobs/templates/periodics/label_sync.tpl
  prow/jobs/templates/periodics/lifecycle_bot_periodic_close.tpl
  prow/jobs/templates/periodics/lifecycle_bot_periodic_rotten.tpl
  prow/jobs/templates/periodics/lifecycle_bot_periodic_stale.tpl
  prow/jobs/templates/periodics/upgrade-go-version.tpl
  prow/jobs/templates/postsubmits/ack-chart_release.tpl
  prow/jobs/templates/postsubmits/codegen_release.tpl
  prow/jobs/templates/postsubmits/community_docs.tpl
  prow/jobs/templates/postsubmits/controller_bootstrap_update.tpl
  prow/jobs/templates/postsubmits/controller_release.tpl
  prow/jobs/templates/postsubmits/runtime_release.tpl
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/controller_bootstrap_test.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
  prow/jobs/templates/presubmits/test_infra_tests.tpl
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
  prow/jobs/tools/cmd/main.go
Labels: approved, lgtm

#471 Fix YAML indentation in jobs.yaml generator
  prow/jobs/jobs.yaml
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
  prow/jobs/templates/presubmits/test_infra_tests.tpl
Labels: approved, lgtm

#472 Patch `prow-docs` to test `prow-build-prow-images`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#473 Revert "Patch `prow-docs` to test `prow-build-prow-images`"
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#474 Fix indentation error in build-prow-images template
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/prow-job-patcher.tpl
Labels: approved

#475 Patch `prow-docs` version to `0.0.10`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved

#478 Fix bug in build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/prow-job-patcher.tpl
  prow/jobs/tools/cmd/command/generator/generator.go
  prow/jobs/tools/cmd/command/patch_prowjobs.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#479 Test `build-prow-images` job
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#480 Add AWS binary to `build-prow-images` job
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/test-infra.tpl
Labels: approved, lgtm

#481 Increase `docs` version to test `build-prow-images`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#482 Fix path issue in `build-prow-images`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#483 Add assume role script for `buiild-prow-images` job
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images/build-images.sh
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/test-infra.tpl
  prow/jobs/tools/cmd/command/build-prow-images.sh
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#484 Test `build-prow-images` job
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#485 Fix `build-prow-images.sh` bash script
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/build-prow-images.sh
Labels: approved, lgtm

#486 Another test for `build-prow-images`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#487 Fix kaniko auth issue with ECR for build-prow-images job
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/patch_prowjobs.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
  prow/jobs/tools/cmd/command/patch_prowjobs_test.go
Labels: approved, lgtm

#488 Regenerate `jobs.yaml` with `build-prow-images-0.0.16`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#489 Fix `upgrade-go-version` template command
  prow/jobs/templates/periodics/upgrade-go-version.tpl
Labels: approved, lgtm

#490 Use `test-infra` repo as work directory for `upgrade-go-version` prow job
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/periodics/upgrade-go-version.tpl
Labels: approved, lgtm

#491 Fix `upgrade-go-version` job template to make `test-infra` workdir
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/periodics/upgrade-go-version.tpl
Labels: approved, lgtm

#492 Fix kaniko dependency issues and github source files path
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/test-infra.tpl
  prow/jobs/tools/cmd/command/build-prow-images.sh
  prow/jobs/tools/cmd/command/github.go
  prow/jobs/tools/cmd/command/helpers.go
  prow/jobs/tools/cmd/command/patch_prowjobs.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
Labels: approved, lgtm

#493 Testing `build-prow-images`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#494 Fix github source file path issue
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/github.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#495 Patch `upgrade-go-version` prow job
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#497 Fix github.go source files path issue
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/github.go
  prow/jobs/tools/cmd/command/patch_prowjobs.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#498 Bump `upgrade-go-version` to 0.0.3
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#500 Fix `github.go` source file path issue
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#501 Patch `upgrade-go-version` prow job to `0.0.4`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#504 Fix `upgrade-go-version` prow job template typo and refactor command
  prow/jobs/images_config.yaml
  prow/jobs/templates/periodics/upgrade-go-version.tpl
  prow/jobs/tools/cmd/command/helpers.go
  prow/jobs/tools/cmd/command/upgrade_go_version.go
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
Labels: approved, lgtm

#503 updating olm-pr-bundle to add ci.yaml file, if it is found missing
  cd/olm/olm-bundle-pr.sh
Labels: approved, lgtm, ok-to-test

#508 Switch from kaniko to buildah for building prow images
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/templates/postsubmits/test-infra.tpl
  prow/jobs/tools/cmd/build-prow-images.sh
  prow/jobs/tools/cmd/command/patch_prowjobs.go
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#509 Patch `build-prow-images` and regenerate `jobs.yaml`
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/templates/postsubmits/test-infra.tpl
Labels: approved, lgtm

#510 Bumb `docs` version to `0.0.11` to test `build-prow-images`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#511 Fix `build-prow-images` script to use correct publish arn
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  prow/jobs/tools/cmd/build-prow-images.sh
Labels: approved, lgtm

#512 Bumb docs version to 0.0.11 to test build-prow-images
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#514 Set vfs as storage driver env for `build-prow-images` job Dockerfile
  prow/jobs/images/Dockerfile.build-prow-images
Labels: approved, lgtm

#516 Bump `build-prow-images` version to `0.0.33`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
Labels: approved, lgtm

#517 Fix build command for `build-prow-images`
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#518 Rename prow job Dockerfiles
  prow/jobs/images/Dockerfile.integration-test
  prow/jobs/images/Dockerfile.soak-test
  prow/jobs/images/Dockerfile.unit
  prow/jobs/images/Dockerfile.unit-test
Labels: approved, lgtm

#519 Bumb `docs` job to `0.0.12` to test `build-prow-images`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#520 Modify `soak-test` Dockerfile
  prow/jobs/images/Dockerfile.soak-test
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#521 Fix `upgrade-go-version` Dockerfile
  prow/jobs/images/Dockerfile.upgrade-go-version
Labels: approved, lgtm

#522 Enhance prow build images logging and build system
  prow/jobs/images/Dockerfile.build-prow-images
  prow/jobs/images_config.yaml
  prow/jobs/templates/postsubmits/test-infra.tpl
  prow/jobs/tools/cmd/build-prow-images.sh
Labels: approved, lgtm

#524 Add `upgrade-eks-distro-version` prow job
  build_config.yaml
  prow/jobs/images/Dockerfile.upgrade-go-version
  prow/jobs/images_config.yaml
  prow/jobs/templates/periodics/upgrade-eks-distro-version.tpl
  prow/jobs/tools/cmd/command/helpers.go
  prow/jobs/tools/cmd/command/upgrade_eks_distro_version.go
  prow/jobs/tools/cmd/command/upgrade_eks_distro_version_helper.go
  prow/jobs/tools/cmd/command/upgrade_go_version.go
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
Labels: approved, lgtm

#527 Remove prow image versions after `eks-distro-upgrade`
  prow/jobs/images_config.yaml
  prow/jobs/tools/cmd/command/upgrade_eks_distro_version.go
  prow/jobs/tools/cmd/command/upgrade_eks_distro_version_helper.go
Labels: approved, lgtm

#529 Bump prow integrations image version
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#464 Add Prow job to verify licenses and `ATTRIBUTION.md` files
  cd/scripts/verify-attribution.sh
  prow/jobs/images/Dockerfile.verify-attribution
  prow/jobs/images/build-images.sh
  prow/jobs/images_config.yaml
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
Labels: approved, lgtm

#532 Add Prow job to detect CVEs in ACK supported AWS service controllers
  prow/jobs/images/Dockerfile.scan-controllers-cve
  prow/jobs/images_config.yaml
  prow/jobs/templates/periodics/scan-controllers-cve.tpl
  prow/jobs/tools/cmd/command/github.go
  prow/jobs/tools/cmd/command/scan_controllers_cve.go
  prow/jobs/tools/cmd/command/scan_controllers_cve_helper.go
  prow/jobs/tools/cmd/command/scan_controllers_cve_tests.go
  prow/jobs/tools/cmd/command/upgrade_go_version.go
  prow/jobs/tools/cmd/command/upgrade_go_version_helper.go
Labels: approved, lgtm

#533 Change `scan-controllers-cve` image build context
  prow/jobs/images_config.yaml
  prow/jobs/tools/cmd/command/patch_prowjobs_helper.go
Labels: approved, lgtm

#534 Update olm-test to `prow-olm-test-0.0.5`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#535 Enhance `verify-attribution` Dockerfile
  prow/jobs/images/Dockerfile.verify-attribution
Labels: approved, lgtm

#536 Temporarily remove `scan-controllers-cve` to allow `build-prow-images` build
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#538 Update olm-test to `olm-test-0.0.7`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#540 Enhance `scan-controllers-cve` unit-tests
  prow/jobs/images_config.yaml
  prow/jobs/tools/cmd/command/scan_controllers_cve_helper.go
  prow/jobs/tools/cmd/command/scan_controllers_cve_tests.go
Labels: approved, lgtm

#542 Update `olm-bundle-pr` to `prow-olm-bundle-pr-0.0.8`
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#544 Update `OWNERS_ALIASES.txt`
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, approved

#547 fix `scan-controllers-cve` job command template
  prow/jobs/templates/periodics/scan-controllers-cve.tpl
Labels: approved, lgtm

#548 Add pre-submit service account to `attribution_gen` job
  prow/jobs/jobs.yaml
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
Labels: approved, lgtm

#549 Copy executable `wrapper.sh` to $PATH for `verify-attribution` job
  prow/jobs/images/Dockerfile.verify-attribution
  prow/jobs/images_config.yaml
Labels: approved, lgtm

#551 Modify template command for verify-attribution job
  prow/jobs/jobs.yaml
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
Labels: approved, lgtm

#552 Change the `Shebang` for `verify-attribution.sh` to `sh`
  cd/scripts/verify-attribution.sh
Labels: approved, lgtm

#553 Change base image for `verify-attribution` job to debian
  cd/scripts/verify-attribution.sh
  prow/jobs/images/Dockerfile.verify-attribution
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
Labels: approved, lgtm

#554 Update `verify-attribution` image and correct bash paths
  prow/jobs/images_config.yaml
  prow/jobs/templates/presubmits/code_generator_tests.tpl
  prow/jobs/templates/presubmits/pkg_tests.tpl
  prow/jobs/templates/presubmits/runtime_tests.tpl
  prow/jobs/templates/presubmits/service_tests.tpl
Labels: approved, lgtm
