Repository aws-controllers-k8s/test-infra, pull requests merged in 2024-01, with the labels that each got.

#407 fix(elbv2): remove nlb dependency on get_bootstrap_resources()
  src/acktest/bootstrapping/elbv2.py
Labels: approved, lgtm, needs-ok-to-test

#408 fix(elbv2): correct import for VPC module
  src/acktest/bootstrapping/elbv2.py
Labels: approved, lgtm, needs-ok-to-test

#409 Tweak integration tests CPU/memory requests and limits
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jinja/presubmits/test_infra_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#411 Adjut memory/cpu requests and limits for all the prow jobs
  prow/jobs/jinja/periodics/label_sync.jinja2
  prow/jobs/jinja/periodics/lifecycle_bot_periodic_close.jinja2
  prow/jobs/jinja/periodics/lifecycle_bot_periodic_rotten.jinja2
  prow/jobs/jinja/periodics/lifecycle_bot_periodic_stale.jinja2
  prow/jobs/jinja/postsubmits/ack-chart_release.jinja2
  prow/jobs/jinja/postsubmits/codegen_release.jinja2
  prow/jobs/jinja/postsubmits/community_docs.jinja2
  prow/jobs/jinja/postsubmits/controller_bootstrap_update.jinja2
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jinja/postsubmits/runtime_release.jinja2
  prow/jobs/jinja/presubmits/code_generator_tests.jinja2
  prow/jobs/jinja/presubmits/controller_bootstrap_test.jinja2
  prow/jobs/jinja/presubmits/pkg_tests.jinja2
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jinja/presubmits/test_infra_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#417 Calibrate CPU/Memory limits based on the latest observations
  prow/jobs/jinja/postsubmits/codegen_release.jinja2
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jinja/presubmits/code_generator_tests.jinja2
  prow/jobs/jinja/presubmits/pkg_tests.jinja2
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jinja/presubmits/test_infra_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#418 Increase memory for rarely failing jobs
  prow/jobs/jinja/postsubmits/ack-chart_release.jinja2
  prow/jobs/jinja/postsubmits/codegen_release.jinja2
  prow/jobs/jinja/postsubmits/community_docs.jinja2
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jinja/presubmits/code_generator_tests.jinja2
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#419 Add `documentdb` labels and prow jobs
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#420 Update public repositories catalog data
  scripts/ecr-templates/ecr-chart-template.json
  scripts/ecr-templates/ecr-controller-template.json
  scripts/public-ecr-set-catalog.sh
Labels: approved, lgtm

#421 Add `efs-controller` labels and prow jobs
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#422 Register more test controllers for ACK `code-generator` PRs
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#423 Setup infra for CARM tests
  prow/jobs/images/wrapper.sh
  prow/jobs/images_config.yaml
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
  scripts/lib/aws.sh
  scripts/pytest-image-runner.sh
Labels: approved, lgtm

#424 Omit `ulimit` calls in docker-ce init.d script
  prow/jobs/images/Dockerfile.integration
Labels: approved, lgtm

#425 Propagate CARM_TESTS_ENABLED environement variable
  prow/jobs/images/wrapper.sh
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
  scripts/lib/aws.sh
Labels: approved, lgtm

#426 Run CARM tests on code-generator PRs
  prow/jobs/jinja/presubmits/code_generator_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#427 Speed up controller auto-generation on code-gen/runtime new releases
  cd/auto-generate/auto-generate-controllers.sh
Labels: approved, lgtm

#416 Bump controller-tools version to v0.14.0
  prow/jobs/images/Dockerfile.integration
  prow/jobs/images/Dockerfile.olm-bundle-pr
  prow/jobs/images_config.yaml
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved
