Repository aws-controllers-k8s/test-infra, pull requests merged in 2024-02, with the labels that each got.

#428 Bump Go version to `1.22.0` in all the build/test images
  prow/jobs/images/Dockerfile.auto-generate-controllers
  prow/jobs/images/Dockerfile.auto-update-controllers
  prow/jobs/images/Dockerfile.deploy
  prow/jobs/images/Dockerfile.olm-bundle-pr
  prow/jobs/images/Dockerfile.olm-test
  prow/jobs/images/Dockerfile.test
  prow/jobs/images/build-images.sh
  prow/jobs/images_config.yaml
  prow/jobs/jinja/postsubmits/controller_release.jinja2
  prow/jobs/jinja/presubmits/service_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved

#429 Add `efs` and `acm` to code-generator tests
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#430 Delegate label management to prow `label_sync` job
  cd/auto-generate/auto-generate-controllers.sh
  cd/auto-update/project-static-files.sh
  cd/olm/olm-bundle-pr.sh
  prow/jobs/jinja/config/label_sync.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#431 Add `documentdb` to code-gen test matrix
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#433 Set CARM environement variables for acktests prowjobs
  prow/jobs/jinja/presubmits/test_infra_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#432 Bump boto3 version to `1.34.39` for `acktest` library
  requirements.txt
Labels: approved, lgtm, ok-to-test

#434 Add `ecs` and `elbv2` prowjobs and labels
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#436 Add new prowjobs to execute e2e tests for runtime PRs
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/jobs_config.yaml
  prow/jobs/labels.yaml
  scripts/controller-setup.sh
Labels: approved, lgtm

#437 Remove redundant refs from runtime e2e prowjobs
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#438 Correct org/repo names for runtime e2e tests prowjobs
  prow/jobs/jinja/presubmits/runtime_tests.jinja2
  prow/jobs/jobs.yaml
  prow/jobs/labels.yaml
Labels: approved, lgtm

#439 Set karpenter provisioner `ttlSecondsAfterEmpty` to 15minutes
  flux/karpenter-config/provisioner.yaml
Labels: approved, lgtm

#443 Remove ultra large instances from karpenter pool.
  flux/karpenter-config/provisioner.yaml
Labels: approved, lgtm
